### ISSUE TITLE
Error checking axes or buttons in Input Viewer

### ISSUE THREAD

**Issue by Jawada74** [muchimi/JoystickGremlinEx#1]
I get the the following error message when I check the follwoing
![Screenshot 2023-06-21 215635](https://github.com/muchimi/JoystickGremlinEx/assets/15045839/021d90b4-2701-4615-bb9b-57d8ee681790)

This does not happenwith the original jostick gremlin.
Any ideas?
Regards

**Comment by muchimi** [comment]
Hi, I'll look at this shortly.  Thank you for reporting it.

**Comment by Jawada74** [comment]
Take your time !
Thanks for your effort

I see you in the verse.

**Comment by muchimi** [comment]
13.39 update issued.
This was a part of the code I didn't look very much into assuming it was working as before.
However the QT6 framework deprecated some older features of the QT API and caused two problems I could find.
One was an exception related to the use of flags and incorrect type casting.
The other was the selected inputs were never active also because of a change in QT.

Please give it a whirl and I'll re-open the issue if the problem persists.   The screenshot helped a lot, thanks.

**Comment by Jawada74** [comment]
It works now  as intended !!! THX.
![image](https://github.com/muchimi/JoystickGremlinEx/assets/15045839/fcabfed2-9e00-4e98-bbc5-1ed4271b85e0)
