### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#10]
@muchimi 
Sorry for being obtuse on this.  But what's the proper way to install this thing?
Do you just put the folder in Program Files and run the executable?  Well that doesn't work and just produces an error.
Sorry if this is obvious and I missed it, but could you provide installation instructions?  Especially if one wanted to run the original Joystick Gremlin version along-side this new Branch version?  For testing etc.

Thanks

**Comment by muchimi** [comment]
The installation is similar to how you install the regular Gremlin.
The zip file (release) has an exe.  Drop the contents of the zip file in a read/write location somewhere (I just c:\joystick gremlin) - avoid Program Files because these are protected areas and will give you issues with UAC (user access control) in some cases.

The exe is all you need to run - no other software is needed, although you may want to install Python 3.11.

Cheers,

M

**Comment by guimoal** [comment]
Hi, I have installed the program but when I initialize the joystick_gremlin.exe, they execute but 2 seconds later close automatically.
[debug.txt](https://github.com/muchimi/JoystickGremlinEx/files/14936354/debug.txt)
 debug.txt is create but in the debug fille i cant view errors. Can you help with this issue?

**Comment by muchimi** [comment]
There is nothing to install.   The release extracts files to a folder and you run the .exe but you do need to make sure the dependencies are installed per the guide (so HIDHide and VJOY) - links provided in the docs and they come with their own installation instructions that are separate from Gremlinex.

I don't recommend installing this to a protected folder such as C:\Program Files  because Microsoft considers these "protected" so UAC may get in the way of things running well.

On my computers, I place the files in the release in a folder in C:\JoystickGremlinEx  if this helps.

VJoy has to be installed and configured before running Gremlin or it won't find the VJOY layers it needs.

HIDHide should be configured after you installed VJOY and GremlinEx so you can exempt the .EXE from the device filtering.
Lastly, as with regular Gremlin, GremlinEx should run with elevated privs so it can send keyboard and mouse data to other processes (games).  If you run it without elevated access, the keyboard and mouse output may not work.

Hope this helps!

**Comment by ZK-273** [comment]
Muchimi,

Sorry if this is obvious.
Please remind.

What if one is already running 'Regular' JSGremlin with HidHide/VJoy
already on the system?

 Is there anything further that should be performed besides Installing and
running GremlinEX in its own C: folder?

Can they be run at the same time?

Is the existing 'Regular' JSGremlin profile compatible with JSGremlinEX?

Sorry and thanks again.

**Comment by muchimi** [comment]
You can run both, but not at the same time (meaning, running them concurrently) - you mean - install I'm sure.
You may run into dragons for a couple of reasons:
- GremlinEx is 64 bit, so requires the 64 bit version of VJOY, which is normally installed with VJOY.  This may cause problems a Gremlin is much older at this point and uses an older version of VJOY.   Gremlin should however work with a more current version of VJOY as Gremlin was fixed a while back by Whitemagic to accept future releases of VJOY.
- The version of python is different, GremlinEx uses 3.11 64 bit, Gremlin uses an older 32 bit version.  This should not be a problem but could open the door to conflicts.


So in principle, yes, you can have both Gremlin and GremlinEx installed at the same time, only run one at a time please, and note that the profiles used by GremlinEx have information what won't be understood by Gremlin so they are not interchangeable, so make sure your profiles are named differently as I think they'll end up in the same folder.

Cheers,

M

**Comment by muchimi** [comment]
Closing this topic.
