### ISSUE TITLE
13.40.14ex (m18) - Recommendation, Lower default Map to keyboard pulse value to 50msec

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#107]
As per title.

Games like Star Citizen with embedded Short / Long push logics get confused with 250ms resulting in pulses being recognized as long push when using 250ms.

Reducing the default to 50msec solves it.

**Comment by muchimi** [comment]
Thanks for sharing the setting. 
Some game loops handle short triggers well, while others do less well.

**Comment by muchimi** [comment]
From many game loops, 200ms to 250ms appears to be the "capture" timer.
Some games are less, some games are more.
The default can easily be changed to even no delay if needed, it's really application dependent.

A possible enhancement is to make it remember the last pulse or interval setting so that when new actions are added, it re-uses the settings from the last numbers.

**Comment by muchimi** [comment]
m21 includes a feature for the keyboard mapper to remember the last set values for pulse and interval so any new action will use the last used values.
