### ISSUE TITLE
JG 13.40.15ex (m2.5) - Mode manager, Profile start mode results in Uncaught exception

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#131]
A blank profile was created and the mode manager menu accessed via the options.  A second mode 'test' was created successfully:
![image](https://github.com/user-attachments/assets/af296ac5-168d-4602-b30d-d0bbd56b5866)

The Profile start mode option was selected to make 'test' the start mode.  The following error was displayed:
![image](https://github.com/user-attachments/assets/b161f727-1a2a-47d6-81a0-0be259b61445)

Workaround:
(1) Save the profile.
(2) Re-enter the manage mode menu and change the default.

It appears that the profile has to be saved first before the change can be made.

Prio: Low
Severity: Low

**Comment by muchimi** [comment]
Indeed a new profile does not have a file saved.
Added a pair of message boxes to that effect and require items that require a profile to exist before executing to avoid saving to a file that doesn't exist.
This cannot be automated either because a file name cannot be derived.  I suppose it could save to a temporary file but right now - save first.
Good catch.

Fixed in m2 hotfix 6
