### ISSUE TITLE
13.40.15ex (m5.1)

### ISSUE THREAD

**Issue by Raz0rLegend** [muchimi/JoystickGremlinEx#150]
Hey again ! :)

Sorry, i know you can't reproduce it...

As the previous version, the axes not responding. It happened only the m4_4 and the m5.1.
Don't know why, but i start from the begining, i even reset my vjoy setup, but no news...

![image](https://github.com/user-attachments/assets/63279c7f-7a13-4833-b0c4-f2d6778e5f22)

![image](https://github.com/user-attachments/assets/de8398f4-37b7-4483-885b-9997dc8384ab)

EDIT

Without the broadcast my joy's are parfect.

![image](https://github.com/user-attachments/assets/e8fbd745-807c-43a0-b164-6477e5054e0c)

**Comment by muchimi** [comment]
Curious.  Does it function with the profile running (open the input viewer window, then run the profile).
Does it work then?

**Comment by muchimi** [comment]
I say this because from the screen shots, it looks like you are mapping the input of the VKB to a device, and the output will of course only happen when the profile is running, so it's "normal" to have no output unless the profile is running.
I'm only going from the screenshots so perhaps not the whole story...

**Comment by Raz0rLegend** [comment]
Yes it's running... You're right, i left it on the screen, i'm an idiot.

![image](https://github.com/user-attachments/assets/4a88da80-bc7e-4719-b5e7-a866f8cc529e)

**Comment by muchimi** [comment]
Yes this is very strange.
Just tested using my Virpils and MFG:
![image](https://github.com/user-attachments/assets/b20ab482-ee5c-4d8c-a270-dc2d6f85d333)

**Comment by muchimi** [comment]
Process of elimination:
You are using the legacy mapper - does it change if you use "Vjoy Remap" vs the legacy "Remap"?

**Comment by muchimi** [comment]
Also, does it work if you use VjoyMonitor (rather than the input viewer in GremlinEx?

**Comment by Raz0rLegend** [comment]
> Process of elimination: You are using the legacy mapper - does it change if you use "Vjoy Remap" vs the legacy "Remap"?

It works right now... I didn't know this option "Vjoy remap"

**Comment by muchimi** [comment]
Good to know, good to know.  The legacy mapper should function for output so I will look into that.  I don't spend much time on the legacy plugins (for obvious reasons) but this function should work. 

For info, GremlinEx has updated versions of actions (and one container so far) that have enhanced functionality as they take advantage of features not previously available.   Many of these features also eliminate the need for additional actions because the behavior is built-in. 

They are:
remap -> Vjoy Remap
map to keyboard -> map to keyboard ex
map to mouse -> map to mouse ex
response curve -> response curve ex
tempo -> tempo Ex

**Comment by Raz0rLegend** [comment]
Good to know, thx for your efficency and your job, now i try to fix the HATS issues ! Bu with your past explaination will be fine !

**Comment by muchimi** [comment]
I located the issue with the legacy mapper.  Will be in m5.2.

**Comment by Raz0rLegend** [comment]
So, for the HAT it's the same ? 

I set it like this

![image](https://github.com/user-attachments/assets/cb3bee63-913e-4547-b890-db526e04cd4d)

But doesn't appear on the views

**Comment by muchimi** [comment]
Th

**Comment by muchimi** [comment]
The hat is probably the same.  I am reviewing.

**Comment by Raz0rLegend** [comment]
Just compared the oldest way and the "ex"

not working

![image](https://github.com/user-attachments/assets/0fcf0667-a515-4bf2-a538-aa27e0ea188c)

**Comment by muchimi** [comment]
The hat is not behaving the way it should - will be updated in m5.2.

**Comment by muchimi** [comment]
On either plugin but for different reasons.

**Comment by Raz0rLegend** [comment]
We're working as a team... The hand and the brain. x)

**Comment by muchimi** [comment]
Resolved in https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.15ex_m4/joystick_gremlin_13_40_15_m5_2.zip
