### ISSUE TITLE
Modifier

### ISSUE THREAD

**Issue by Raz0rLegend** [muchimi/JoystickGremlinEx#154]
Hi Muchimi, 

![image](https://github.com/user-attachments/assets/049b802c-fcda-473f-9147-89cdb29d7a34)

When i use a modifier profile mode. To add a new page of rebinds. This is like a temporary switch, BUT it works as toggle.
To resolve this issue, i put this : 

![image](https://github.com/user-attachments/assets/f34ddf45-d71a-4df9-8eca-c694ae85d980)

and this : 

![image](https://github.com/user-attachments/assets/17cf139a-0458-4bcc-ad62-9ece8838a724)

The issue is, it works perfectly as temporary mode switch, but it comes everytime on the SCM Mode, and i just want to have it on the previous mode. 

I explain, if i am on the SCM, i press modifier, press my button and then i come back on SCM.
If i'm on the nav, i press modifiier, press my button, and then i come back on nav (The issue apears here, i come back always on SCM, because of the tree i guess)
if i'm on the aux, i press modifier, press my button, and then i come back on aux ( you understood it, in reality, i come back again on SCM)

Thanks in advance.

Here a gif of the issue.
![opera_gSOuZ11D88](https://github.com/user-attachments/assets/4d287fab-5b71-4c4c-abd7-f432b594c8ef)

The second issue is, when i delete the tree setup, when i use the modifier, it stuck itself on the AUX mode..

![joystick_gremlin_0vJPOnu9YM](https://github.com/user-attachments/assets/8f9726a7-7eae-458a-985a-78d714bc86a8)

**Comment by muchimi** [comment]
The temporary mode action is only temporary and will return to the prior mode when released, and it can get weird in certain conditions.  Can you zip up your XML and attach it here (or paste it as text) or PM me on discord with the info because to determine if a bug or a feature - I need to look at the exact profile "wiring" and for that I need to load your profile to make sure the behavior is as expected.

In general, a temporary mode switch is unlikely to be what you want as you probably (and this is a hunch from my experience) a permanent mode switch based on button state (the state is temporary, the action is permanent - hard to explain!)   There are several ways to do this and my go-to in this case would be to use something like this depending on the state of the input button.  In SC I have one of the hat switches and a fixed button on my throttle wired as a three-way switch for this and it's how I cycle scan/mining/scm etc.

![image](https://github.com/user-attachments/assets/c3680142-6223-4051-9dc7-d39c2e8a781e)

**Comment by muchimi** [comment]
The other recommendation I have is your mode buttons are all "Switch Mode" type actions and only appear in the root mode of your profile, and they are not mapped in any submode.
Depending on the button / inputs you use, the "switch mode" can be mapped as normal to a press/release cycle, for three-way switches you need at least a release somewhere.
I'm actually thinking, because this comes up very often, to have a container that does a switch mapping that handles that logic as every controller handles the input differently and it'd be a lot simpler if we had a container that has a compound button definition, and GremlinEx can do this relatively easily now with the internal API changes.

**Comment by Raz0rLegend** [comment]
Here you have my full profile

[[3.24.2]Profil Definitif HOTASAS VKB-X52.zip](https://github.com/user-attachments/files/17522581/3.24.2.Profil.Definitif.HOTASAS.VKB-X52.zip)

Just so you know, i modify the modes with the red buttons..

![image](https://github.com/user-attachments/assets/bffd7921-c0cc-4b5c-8b21-5d01a134db3f)

**Comment by Raz0rLegend** [comment]
Look what i have on the 13.3 original JG

![joystick_gremlin_151PxsWQhK](https://github.com/user-attachments/assets/1ae8d8fd-bb8f-43d4-a307-c10a890489e1)

And now it works perfecly with this version.

**Comment by muchimi** [comment]
Thanks for the info.
So looking at this, you are using the older tempo container and cycle modes.
I was able to import your profile (which reminds me I need to do another pass on the import feature for mode mapping specifically).
I already found one issue is the tempo container reports it is invalid in GremlinEx so it doesn't run at all (so it's not even getting to the mode changes).  More in soon (tm).

**Comment by muchimi** [comment]
Proposed enhancements in the link below.

https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m1.zip

**Comment by Raz0rLegend** [comment]
Tried, but the VjoyrRemap brings an error. 

![image](https://github.com/user-attachments/assets/28d06915-d3bc-426c-a439-77e666245ad2)

Is she frome my side ?

**Comment by Raz0rLegend** [comment]
So i had an issue, but it was my side, Vjoy issue.

Actualy with the tempoex, it does the same, so no come back on the good profile. Always, on the first one. I show it to you tto verify..

![image](https://github.com/user-attachments/assets/326afde6-d954-494c-b200-dc9244e28a15)
![image](https://github.com/user-attachments/assets/f97edd0e-79c2-4abc-a122-75417b032dbc)

**Comment by Raz0rLegend** [comment]
![joystick_gremlin_UXAbUD50Mw](https://github.com/user-attachments/assets/94b2c522-2dcb-4325-8562-81d04ca8e94e)

Here the video with the logs.. The cycle mode works perfect. The modifier brings some errors and stay stucked.

**Comment by muchimi** [comment]
I didn't encounter a GUID error when I tested on my system using your container setup but it could be something else.
The error you see is not because of a container/action issue but because the output ID of the vjoy device doesn't exist (it used to blow up, now it gives you an error "I can't find the output device you are looking for".
The question is why it cannot be found - this could be because the profile needs to be remapped / updated or possibly a mapping issue.
One idea is as the profile starts and I can make sure the output device still exists.

Perhaps you can describe in words what you are expecting the behavior to be - starting with "I press this and I want that to happen" then "I press this again and I want this other thing to happen".

That will let me duplicate that logic.  I loaded your profile and based on the options in the XML - it does exactly what I'd expect it to do so I'm clearly missing something here lol and off in the pastures.

**Comment by Raz0rLegend** [comment]
Actualy, it happens when i push to button to change the mode, between SCM / NAV / AUX

When i psuh the modifier, i would like to add a new serial of buttons, but when i unpress the modifier, i would like to stay on the mode i was.
Like this SCM > modifier > SCM
SCM > NAV > modifier > NAV ....

**Comment by muchimi** [comment]
Ok so to make sure I understand this correctly, you want to press a button that temporarily changes the mode to "modifier" and when that button is released - returns to the mode it was at before the temporary switch?

Startup mode = SCM -> press button 3 -> go temporarily to modifier mode -> release button 3 -> return to SCM mode.
Press button (3?) -> change from SCM to NAV mode -> press button 3 -> go temporarily to modifier mode -> release button 3 -> go back to NAV mode

Is that right?

**Comment by Raz0rLegend** [comment]
SCM > press 3 Cycle mode > NAV > press 5 temporary switch to modifier > modifier > unpress 5 back to the previous > NAV

**Comment by muchimi** [comment]
Ok got it - I need to look this up later as I need to step away for a bit - in the mean time - wanted to verify that you have button 5 using the temporary mode switch action, and not the cycle mode action?
The Cycle Mode action you use is meant to change modes through a list everytime you press the button - all your actions have a single mode in there so you probably really want the "change mode" action rather than "cycle mode", and for the temporary one, the "temporary mode" action.

I'll look into this when I get back.

**Comment by Raz0rLegend** [comment]
![image](https://github.com/user-attachments/assets/d6522545-a822-4f58-a86a-13c414320424)
![image](https://github.com/user-attachments/assets/3455ebc5-a9e9-4d44-a326-730f77c31585)

It's that yes.

**Comment by muchimi** [comment]
After tracing through this specific use-case, I updated the logic for the cycle action widget as well as the temporary mode widget to reflect the additional functionality in GremlinEx.

https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m3.zip

Starting with this mode configuration:
![image](https://github.com/user-attachments/assets/806bb7ed-be45-487b-90fc-24d7f7d3af51)

Adding this mapping to button 3 to the default SCM mode (and not mapped in any other mode)
![image](https://github.com/user-attachments/assets/f7ee257d-ef45-4959-8640-5f313736862b)

Adding this mapping to button 5 to the default SCM mode (and not mapped in any other mode):
![image](https://github.com/user-attachments/assets/9f81d27b-634b-4d0e-b227-cf9d5ba111bf)

on my system produces the following behavior in m3:
- profile starts in SCM mode
- pressing button 3 toggles to the next mode (SCM->NAV, NAV->SCM)
- pressing button 5 in any of the modes selects MODIFIER mode while button 5 is down, and returns it to the mode it was at the time button 5 was pressed.

Before the code fixes, temporary mode switch would return to the default mode which is incorrect, but it was correct at one time before some other back-end logic changed.

**Comment by Raz0rLegend** [comment]
Atm, it works perfectly ! I tried everthing and it's good ! I will remap it with the vjoyremap and i'll send you a return. :)
