### ISSUE TITLE
Can you make the profile NOT deactivate when a device is removed/turned off?

### ISSUE THREAD

**Issue by Spidey002** [muchimi/JoystickGremlinEx#17]
I use Joystick Gremlin for Elite Dangerous, and I use my Xbox controller for on-foot gameplay.
But when I'm in my ship, if my controller turns off, I lose all the bindings and curves I have set.

I discussed this on the issues section of the original JG. And someone had a solution, but I don't know how to implement it.
https://github.com/WhiteMagic/JoystickGremlin/issues/276#issuecomment-1221171514

**Comment by muchimi** [comment]
This is difficult because the list of HID devices is initialized when Gremlin runs, and the code is not currently setup to handle disconnects while it's running (or additions for that matter).  This has to do with the HID layer and scripting (scripts get initialized and can reference devices it wants to find, and if it doesn't after you run the code, there will be an exception which will stop the profile from running).

It may be possible in the future but would require a major rewrite of the base code.

So currently - the answer is unfortunately no but I have this on the wishlist, thanks for mentioning it.

**Comment by ZK-273** [comment]
@Spidey002  It may not be ideal, but could you just have the controller connected via USB cable?  This to ensure at least (if it's wireless) that power will still be going to the controller.

Take a look at this link as well:
https://alvarotrigo.com/blog/xbox-keeps-disconnecting/

Could be also in your device manager windows might turn off the controller i.e. Power Mgmt settings.

**Comment by vovik8** [comment]
+1 Having the same problem using a Bluetooth gamepad (8bitdo zero 2)

The PC autostarts with Stepmania and my dancepad attached via usb, but when I then go to turn on the Bluetooth gamepad JoyStickGremlin turns off vJoy mapping.

**Comment by muchimi** [comment]
I am not using a gamepad, so it's hard for me to dive into the issue.
GremlinEx will work with any HID DirectInput device that enumerates as joystick (so something with axis and buttons) and shows up in the Windows applet (when HID Hide is not enabled) joy.cpl.    If you run joy.cpl (windows key + R, type joy.cpl in the command line, hit enter) - it should work without issue.   This may require your gamepad to be configured not as a gamepad, but a joystick.   Again I've not attempted this because I don't use a gamepad so cannot test it.

Microsoft decided years ago that gamepads have a different DirectX input path and this has caused issues since day one with gamepads not working as joysticks, and vice versa.

I can consider looking at gamepads but since I don't have any - it may be difficult.  I remember seeing something about some utilities that make gamepads work as normal HID devices so that may be an option there, and the guys behind HIDHIde make a tool for this IIRC for this specific reason.

**Comment by Spidey002** [comment]
The main issue is that when my Bluetooth connected controller turns itself off (because I’m using my joystick), Joystick Gremlin turns off the active profile. So any curves or key mappings I have set turn off.

And when I turn the controller back on (because now I need it), the profile turns off again.

I play Elite Dangerous with a Hotas, but switch to a controller for on-foot activities.

**Comment by muchimi** [comment]
The default behavior if Gremlin is running a profile and the device no longer exists is to exist because directX throws an exception (the device can no longer be read, so the input is no longer valid, therefore the profile cannot continue running as is).

I am not sure if there is an option to ignore inputs that dropped off while a profile runs - this is odd behavior to start with as you'd have a similar issue with a game and reconnecting (a good example of this is TrackIR - if it stops running - you can't usually re-start it without restarting the game).

Part of the issue is the error is thrown at the DirectX layer.  I'm sure there are some things that could be done about this but the expectation is devices don't get turned on or turned off without a profile reset.

If the change is so significant - Gremlin has to be restarted because the issue is also going to impact device hiding for example.

This is not a simple topic.  I'll keep it open for now.

**Comment by muchimi** [comment]
Update: I have traced the issue back to the VjoyInterface.DLL that throws an error when a device is connected/disconnected while a profile is active.  Looking for options in JGEX to handle more gracefully than throwing an error of its own when this happens.
