### ISSUE TITLE
vJoy axes wrong

### ISSUE THREAD

**Issue by Lucarrrrr** [muchimi/JoystickGremlinEx#170]
With v13.40.16m10 or earlier one of my vJoy axes were identified wrong: x,y,z and rx instead of x,y,rx and ry. Ry was assigned as y. The only workaround was to change the vJoy axe from ry to z (Image 1. For consistency I want to correct it (Image 2) because it's defined as those by the device (Image ICP).
It's not recognized after the change (Image 3) and reboot.
In the Settings the axes are shown correct (Image 4), but cant be choosen.
Any idea to reread the axes information?

![1](https://github.com/user-attachments/assets/92a922c1-1c50-4398-af1a-212e710db5bf)
![2](https://github.com/user-attachments/assets/eca88ca5-c88b-4a11-bc01-5bf07e89eaf4)
![3](https://github.com/user-attachments/assets/db058225-1b17-4d6b-81d4-544f2fde6b8b)
![ICP](https://github.com/user-attachments/assets/d8aae1c7-677c-44ef-9a9e-3500d11464ef)
![4](https://github.com/user-attachments/assets/b36d1c5d-a94d-4f15-a957-0a3731e0cbb0)

**Comment by Lucarrrrr** [comment]
![ICP2](https://github.com/user-attachments/assets/d2c0f2c0-9aac-4b70-b4e4-85ca0abbc382)

**Comment by muchimi** [comment]
In GremlinEx, which uses DirectInput, the axes are read in the sequence they appear in DirectInput, up to 8 axes.  I've looked and it doesn't appear that the axis usage is read by DirectInput as it doesn't expose that information (I spend some time today looking at the API documentation and the C++ header).  That data does exist at the USB descriptor level but not apparently in DirectInput, and GremlinEx does not read USB devices, it uses DirectX to do this, so we're limited by what DirectX provides, which is the count of devices.   I'm going to look into this some more because there is an axis mapping structure returned, and I need to see if it skips an index which we can then use).  

So when you say the axis name is wrong, you are completely correct in that the name is based on the sequence, and the "normal" sequence is X, Y Z, RX, RY, RZ, S1, S2 for the 8 axes.  If you skip a sequence, GremlinEx won't be the wiser.

This said, I need to understand why it matters.  Looks like you're using a winwing control panel - I don't have one of those so not sure how the mapping works but for now, use the sequence (number) of the axis rather than the name as the name is essentially arbitary and not used is any mapping, the index of the axis however is.

I'll do some more digging but yes, the name is based, for now, on no gaps in the sequence.  It only looks for the first eight axes.

**Comment by muchimi** [comment]
I configured a device similar to yours with a skipped axis and I think I have a way to get the name by comparing the axis sequence number to the mapping slot.  That may be the trick needed here.

**Comment by muchimi** [comment]
Here's a first go at this.  Using the mapping data returned, GremlinEx will attempt to derive the correct usage type for the axis as reported by DirectInput's mapping data.  I wish it was possible to get the actual usage flag as coded into the USB device descriptor but that doesn't appear to be feasible, and the other option is to grab that data from the USB descriptor but it could require GremlinEx to have elevated rights and add one more library to the mix - so this is a good compromise and it seems to work based on my testing.

I duplicated your JVOY device and GremlinEx only presented the axes as named in the VJOY configurator.  See if this helps any.

https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m18.zip

**Comment by muchimi** [comment]
Please advise if resolved.
Current patch:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m24.zip

**Comment by Lucarrrrr** [comment]
I solved this problem by adding axis Z so there are 5 in a row now. I want to preserve the original axes like those from the real hardware devices to clearness. I try to  As I have 13+ different controllers for flightsims and try to map real buttons to one oft he 9 vJoys buttons as much as I can. Sometimes it’s difficult to install a new vJoy device without messing up the total system. 

ith this workaround I can live very good. Thanks.

Problem solved for now.

 

Von: muchimi ***@***.***> 
Gesendet: Samstag, 16. November 2024 23:01
An: muchimi/JoystickGremlinEx ***@***.***>
Cc: Lucarrrrr ***@***.***>; Author ***@***.***>
Betreff: Re: [muchimi/JoystickGremlinEx] vJoy axes wrong (Issue #170)

 

Please advise if resolved.
Current patch:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m24.zip

**Comment by muchimi** [comment]
Thanks.
