### ISSUE TITLE
Problem: vJoy axis moves slowly and with a delay

### ISSUE THREAD

**Issue by SyFiD** [muchimi/JoystickGremlinEx#173]
Hello
following your recommendation, I am changing my complete controller assignment to vJoy, and I have encountered the following problem with vJoy device no. 2 and 3.
However, this problem does not occur with vJoy device no. 1.
When assigning an axis to vJoy 2 or 3, it moves very slowly. This behavior also occurs with other axes.
I do not know whether the problem is caused by settings in vJoy or by JG Ex.
If the setting is set to vJoy1, the axis moves normally.
Here is a demonstration on axis 8:
https://github.com/user-attachments/assets/41a902b3-9b0e-453b-b8c9-8dfce6edc6bf

Here are my settings in vJoy:
![vJoy1_Setting](https://github.com/user-attachments/assets/02ab3dd9-f0d4-481f-aeda-71cfdd3d7465)
![vJoy2_Setting](https://github.com/user-attachments/assets/f40b19d1-23ac-4a95-b7ee-db34e3939d48)
![vJoy3_Setting](https://github.com/user-attachments/assets/4390fbfe-6b33-4239-b4e2-05b3e017cbf8)

I think the settings are OK so far, or have I set something wrong?

**Comment by SyFiD** [comment]
This error no longer occurs when testing version **m21**. 
But when loading a profile via import, I now get this error message:
![Import Profile error](https://github.com/user-attachments/assets/7c00294f-fd1a-48ff-ad2a-611380d402f9)

When loading via 'Open Profile', the profile is not loaded at all. But there is also no error message.

**Comment by muchimi** [comment]
Thanks for reporting.
The "slow" response should not happen and is not typically observed unless there is significant logging enabled (or an error occurs in the log file) - the first go-to when you experience a slow response is to look at the log.  Errors and log volume (depending on the log options enabled) can be excruciating and will definitely slow things down - enable detail mode just to see how quickly hundreds of log lines show up).

The runtime is the same for all outputs, so there is no reason for one device to be slower than the other.  It can look slow because of conflicting mappings (that happens if you have two inputs that send conflicting data and cause the slow).  Curves are also a reason for slow response.  All these can be diagnosed easily via the log output, depending on the detail level, to see what it's doing (or not!).

The import feature is still a work in progress and not feature complete, and has taken the backburner route as still a to-do item.   I'll definitely look at this though as this error is linked to the updated general state tracking for buttons and it's looking for button 128 - so you're importing, my guess, a JVOY input device unless you have hardware with 128 buttons :)

**Comment by muchimi** [comment]
Feel free to send me the profile you're importing - I had someone send me a profile with a lot of inputs and modes and this was very helpful to troublehshoot profiles.  It turns out my internal profiles are very, very simple, compared to what you guys come up with - so send me the profile here or in Discord and I'll go through the same motions to pinpoint the issue.  Thank you!

**Comment by SyFiD** [comment]
In the profile I am currently experimenting with, I have 8 axes and 128 buttons in my WinWing hotas (in hardware there are “only” 108 buttons).
At the moment I can't load any older profiles for testing.
I only have a slightly older profile here from June.
With several profiles.
What is your Discord Channel?

[StarCitizen_Gremlin_X56_HOTAS.zip](https://github.com/user-attachments/files/17737188/StarCitizen_Gremlin_X56_HOTAS.zip)

**Comment by muchimi** [comment]
I found the issue.  Fixing for m22 for today's patch.

**Comment by SyFiD** [comment]
Here is the dill_debug.txt
[dill_debug.txt](https://github.com/user-attachments/files/17737269/dill_debug.txt)

**Comment by muchimi** [comment]
Resolved in:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m22.zip

**Comment by SyFiD** [comment]
Yes, is works now!
