### ISSUE TITLE
Tempo vs TempoEX

### ISSUE THREAD

**Issue by Miso581204** [muchimi/JoystickGremlinEx#176]
when I use a 2x middle mouse click with the old TEMPO container, it's ok (I use the function "map to mouse") 
but if I try to do the same thing with TEMPOEX container, the function doesn't work (I use the function "map to mouse EX")

**Comment by muchimi** [comment]
Hi, the two tempo containers behave slightly differently, one reason the old tempo container is still around is the TempoEx adds a few different twists to the concept, so I'm not entirely surprised.

Does the 2x middle mouse click work with the old tempo container with map to mouse, or does it only work with map to mouse ex?

Also, can you describe the behavior you are trying to accomplish?  I assume a double click?  If so, that is one of the modes I want to add to the mouse Ex container (trap double click instead of just single click) because it's come up before that the mouse action should handle a few more "normal" situations, such as double click.

**Comment by Miso581204** [comment]
the 2x middle mouse click work only with the old container and not with the new

**Comment by muchimi** [comment]
Hotfix 16m24 adds a double click option to Map to Mouse Ex if this helps.  
Please let me know if you are still stuck - or if you have a working solution with the containers/actions provided.
You should not expect TempoEx to behave like Tempo - they are a bit different in their behaviors so I'm not surprised.  It's also one reason I have not marked the Tempo container as a legacy container.
The current patch is
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m24.zip

**Comment by muchimi** [comment]
Marking this resolved for now pending new information if we need to re-open.
