### ISSUE TITLE
Joystic axis value versus current JG output

### ISSUE THREAD

**Issue by ktall** [muchimi/JoystickGremlinEx#186]
I like that you set thoses two values. It really help to know when we need a deadzone or not.
Problem is that the value in the mapping is ok but the value in the axis/button selection column is not. see attachment :

in the remap I have a +0.005 C+0.000 => deadzone is effective
in the tab on the left I have +0.005 C+0.005 => direct output

With my gold fish memory, I keep coming to the axis to add a dead zone and... ho I have one. then I do another round around my bowl...

I would say that this datapoint is picked up before the default output curve you added.

![6B2F9E81-8E59-4901-BD19-0BCBEB9FAEC1](https://github.com/user-attachments/assets/cec2d1f9-299d-4744-885f-02c84132429b)

**Comment by ktall** [comment]
Ok I have fould mode inconsistency on this left column :

the default output curve is not consistantly signaled. you can see on the image below that on the current selection I do have a default curve (working dead zone, thanks a lot !) but it's not sown on the axis/button selection tab

same thing for the joystick value vs current value : joystick value is always shown, current value is random

![{72457EED-703A-40AA-848A-5AF69D11086C}](https://github.com/user-attachments/assets/50a3065c-cce1-44a0-a899-8ffc0935974a)

**Comment by muchimi** [comment]
The info on the left reflects the raw input value.
The info on the right reflects the computed output value (or should anyway - had a few hiccups there in the past).

The idea of the left panel is to show what your hardware/input is sending to GremlinEx before any manipulation.  Deadzones and other manips won't be reflected as that uses the raw input value before any processing, and that is by design.

The idea of the right panel (mapping) is to show what the computed output looks like - without actually running the profile which is a fine dance to do between performance and UI responsiveness.

The left panel input repeater started mostly as "which physical axis or button is what" because it drove me crazy with some manufacturers that the axes or buttons are not necessarily in the order they appear on the physical box (looking at you Honeycomb).

**Comment by daganael** [comment]
> The left panel input repeater started mostly as "which physical axis or button is what" because it drove me crazy with some manufacturers that the axes or buttons are not necessarily in the order they appear on the physical box (looking at you Honeycomb).

Totally agree with that ! so the first part of the ticket is closed.
what about the second part ?

**Comment by ktall** [comment]
> The info on the left reflects the raw input value. The info on the right reflects the computed output value (or should anyway - had a few hiccups there in the past).
> 
> The idea of the left panel is to show what your hardware/input is sending to GremlinEx before any manipulation. Deadzones and other manips won't be reflected as that uses the raw input value before any processing, and that is by design.
> 
> The idea of the right panel (mapping) is to show what the computed output looks like - without actually running the profile which is a fine dance to do between performance and UI responsiveness.
> 
> The left panel input repeater started mostly as "which physical axis or button is what" because it drove me crazy with some manufacturers that the axes or buttons are not necessarily in the order they appear on the physical box (looking at you Honeycomb).

can say the same about virpil :P
