### ISSUE TITLE
response curves

### ISSUE THREAD

**Issue by daganael** [muchimi/JoystickGremlinEx#188]
Response curves ex are loaded as legacy when JG starts fresh (closing-reopening app)
No big deal as it doesn't impact JG output but weird enough

See image below, 1min appart

![{37F79A45-92E6-4D41-A619-E55390E8DE43}](https://github.com/user-attachments/assets/dd84a709-353f-4501-9743-1c0ef9a1ad92)
![{7339023A-50AB-4DCA-9FD9-7E0F580684DE}](https://github.com/user-attachments/assets/ca55cc82-88b8-4457-8d52-8365ee46be60)

**Comment by muchimi** [comment]
OOH well that is not supposed to happen is it.  
As you can tell, I don't use the separate mapper because I use the curve in Vjoy to Remap.
Context:  the response curve action can cause very serious trouble with the more complex actions such as gated axis and map to vjoy.  The other thing is that there is a philosophical discussion that enters the fray because the question is "when should the curve be applied", before the action, or after the action?

These existential problems had me add the curve output directly to the input axis, as well as the vjoy mapper because it becomes clear what the curve is applied to.

**Comment by muchimi** [comment]
This is resolved in m28.
