### ISSUE TITLE
Joystick Modifier Button Not Releasing HAT-Triggered Button on Modifier Release

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#206]
This is a little bit tricky to explain:

My joystick configuration has two operating modes: **Normal Mode** and **Shift Mode**. The **Shift Mode** is temporarily activated by pressing and holding the **S4** button on the joystick, which acts as a modifier.

**Normal Mode**: In this mode, the joystick uses "Vjoy Remap" for HAT 1.
**Shift Mode**: In this mode, "Vjoy Remap" is combined with "HAT to Button" functionality.

**_Issue_**:
When **Shift Mode** is activated by pressing and holding the **S4** button and the HAT is held in any direction, the corresponding button is pressed and remains pressed. However, if the **S4** button (Shift) is released while still having the HAT in the same direction, the button remains pressed even after the HAT returns to the center position.

**_Expected Behavior:_**
The corresponding button should be released when the **S4** button (Shift) is released, regardless of the HAT's position.

![image](https://github.com/user-attachments/assets/7b9c82a6-09ba-468d-b66a-311877e3181e)

**Comment by muchimi** [comment]
It is expected behavior and a side effect of the wiring behavior: when you mode change, you also change all mappings so the prior mode "state" is no longer relevant.  In general, the way the wiring works, you need to release the buttons prior to mode change.  Now what you could do, theoretically, 
This said, it is completely feasible to have an option to "release" all buttons on a mode change.  I need to give this more thoughts because on one side you can argue - yes - release the button on mode change - however I also can come up with a number of scenarios where that would be a bad idea.  
It's easy enough to add a setting, as with sticky behavior to release buttons on mode change, the question is more a philosophical one - why is that needed in the first place as I can think of a number of reasons for or against.
