### ISSUE TITLE
(M37) Conditions Do Not Register Release of Joystick Button

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#213]
In the Joystick Gremlin Legacy application, it is possible to have a macro get kicked off if the condition of the release Joystick Button is recognized.  This works fine in JSG Legacy, per below SS:

![image](https://github.com/user-attachments/assets/712d036c-7e90-44e7-a319-902bfde43c5b)

However, in doing the same thing in Joystick Gremlin EX, it fails to operate in the same way, and doesn't recognize the release event of the Joystick button:

![image](https://github.com/user-attachments/assets/7f379e6b-a238-4271-9d2a-068f4c14c518)

**Comment by muchimi** [comment]
Hi ZK - I have a question: what is the purpose of the second action condition on the container?
I ask because you use one legacy feature I don't, so I need to understand what the desired behavior of the condition is to see if that legacy feature makes any sense in how GremlinEx thinks about the input.  By this I mean "when I press this and release this, I expect this".

The behavior duplicating your inputs: it can never work because the virtual button on a button cannot ever be released (by virtue of it having to be pressed in the first place to trigger - so if the input is pressed so the condition fails automatically because it says "the button is pressed" and it can only succeed if "the button is released".

This may be one of those where the legacy feature set differs from the new feature set and I don't know.

To help, I have added a logging option called Verbose Condition that will output copious condition data to the log so it provides you a clear view of what's going on under the hood and why some things succeed and why some fail - either outcome could be correct depending on the desired behavior.  This can generate a lot of data and slow things down but it's often necessary to see what GremlinEx is doing, vs what you think it's doing.  [my experience the code always does what I told it to do even if that's not what I want it to do lol].

As such I cannot find anything that isn't behaving as designed right now for this particular item.  I'd expect the action condition to not be there for this to work at all.

Hopefully this make sense.

**Comment by ZK-273** [comment]
I don't recall the purpose of the second action TBH. (Virtual Button).  I think I was advised a long time ago when trying to make this work, to add it in there.

The actions work in Legacy, and when the Joystick Button is released, the macro will run and release the Right Alt Key and Press down the Left Alt Key and return to the L-ALT [FLIGHT] Mode:
![image](https://github.com/user-attachments/assets/cb84e424-2a00-4fd8-8ec6-aac56d58085e)


This is for mode switching using Virpil Alpha Prime's two-stage Button 4/5 trigger button.

Logic needs to be:

**1. Press Down Button 4:**  (_Button 4 being held as well_)
① Hold down Left Alt Keyboard Key
② Switch to mode L-ALT [FLIGHT]

**2. Press Down Button 5:** (_Button 5 being held as well_)
① Release Left Alt Keyboard Key
② Hold down Right Alt Keyboard Key
③ Switch to mode R-ALT [FLIGHT]

**3. Release Button 5:**
① Release Right Alt Keyboard Key
② Hold down Left Alt Keyboard Key
③ Switch to mode L-ALT [FLIGHT]

**4. Release Button 4:**
① Release Left Alt Keyboard Key
② Switch to mode FLIGHT

The main issue I'm having with Joystick Gremlin EX, is that it's not recognizing the release of Button 4 and 5 so as to release the Left Alt and Right Alt keys from being pressed.

Again, this concept works in Joystick Gremlin Legacy.  I just brough over all the actions etc from Legacy to your version and I've encountered this.

**Comment by ZK-273** [comment]
Upon some further discussion, it seems that the: 'this (virtual) button is Released' as an action condition in the container of the macro is what helps Joystick Gremlin Determine the release of the button, which kicks off the macro to change the mode and press/depress the ALT keys.

This is happening in Joystick Gremlin.  However it is not happening in Joystick Gremlin EX.

**Comment by ZK-273** [comment]
@muchimi With further investigation and help from the community, we can close this, as the driver to this issue was the inability to carry over 1:1 from Joystick Gremlin Legacy  to JSG EX the ability to detect the release of Joystick Buttons and subsequently kick off explicit key presses, key releases and mode changes.

There is an incompatibility in how JSG 32 handles these actions and conditions compared to JSG EX that made it a requirement to use the Temporary Switch Mode in combination with adjusting and using the Virtual Button conditions.
