### ISSUE TITLE
Max recursion depth (13.40.7ex)

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#23]
Unfortunately, 13.40.7 did not solve the max recursion depth error reported on 13.40.4 :

![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/fed4e402-fb13-4145-a09c-ef9e884e36ea)

I can provide replication steps if required.  Here is an example of XML snippet causing the error anytime the axis in question is selected via the GUI :

<axis id="1" description="Thrusters Left / Right">
                    <container type="basic">
                        <action-set>
                            <macro action_id="6cd756e9c7b54001adbc1512089a2e8e">
                                <properties/>
                                <actions>
                                    <vjoy vjoy-id="2" input-type="button" input-id="4" value="True"/>
                                </actions>
                            </macro>
                        </action-set>
                        <virtual-button lower-limit="0.99" upper-limit="1.0" direction="below"/>
                    </container>
                    <container type="basic">
                        <action-set>
                            <macro action_id="a81b32edcd9441538d5c71261100dbf5">
                                <properties/>
                                <actions>
                                    <vjoy vjoy-id="2" input-type="button" input-id="4" value="True"/>
                                </actions>
                            </macro>
                        </action-set>
                        <virtual-button lower-limit="-0.99" upper-limit="-1.0" direction="above"/>
                    </container>
                    <container type="basic">
                        <action-set>
                            <macro action_id="76b8926bb9c84384a517ace74ff90752">
                                <properties/>
                                <actions>
                                    <vjoy vjoy-id="2" input-type="button" input-id="4" value="False"/>
                                </actions>
                            </macro>
                        </action-set>
                        <virtual-button lower-limit="-0.98" upper-limit="0.98" direction="anywhere"/>
                    </container>
                    <container type="basic">
                        <action-set>
                            <vjoyremap vjoy="2" axis="1" mode="VJoyAxis" input="1" axis-type="absolute" axis-scaling="1.0" axis_start_value="0.0" range_low="-1.0" range_high="1.0" reverse="False" action_id="cd7ffd1b443d41649fae8f022c340277"/>
                        </action-set>
                    </container>
                </axis>

This code allows for the activation a the Vjoy#2 button#4 anytime the X axis is moved beyond 99% in either direction.  (It enables auto boost in Star citizen when hitting the stick max aft or fwd limit).

Cheers and many thanks for the continuous work on this awesome program. You're a legend.

**Comment by Lolo401** [comment]
My ecosystem is the following :
- Windows 11 Pro x64,
- Python 3.11.2
- Vjoy 2.1.9.1
- HidHide 1.5.212.0

**Comment by muchimi** [comment]
Ok thanks, I'll take a look - I was really hopping this was the QT race condition.

Side note:  this stuff I don't do in the UI at all because I find it frustrating and hard to setup - but that's also because I've learned how to do this using a small python script, so sharing how I do that if this helps you.

You can see the profile script examples both for MSFS and SC (Star Citizen) now included with the distro.  The SC script has an example of what you are looking to do for the space brake and the boost (which I have mapped on the twist of my left and right sticks respectively).   The example below is for the space brake but can be adapted to any situation like this where you want to send a key while the stick is in a particular range, and stop when it's not.   This is also covered in the MSFS script for various condition lever values - mostly for turboprop aircraft because MSFS's mapper is absolutely horrid when it comes to mapping in general.

The general idea of profile scripts is - anytime there needs to be some sort of logic needed, much faster to do in a script once the config file has been setup (so you've mapped your hardware IDs in config.py - something you only need to do once for all the scripts for all profiles).

The general code for a script that sends a keyboard macro based on a 95% threshold:

`
# send a Z press and send a Z release for space brake on/off based on joystick value
brake_on_macro = Macro()
brake_off_macro = Macro()
brake_on_macro.press("Z")
brake_off_macro.release("Z")

# not needed but here for latching purposes so another routine can tell if brakes are applied
brake_on = False # not braking by default

# @left_vpc is defined in config.py and points to my left virpil stick - the ID comes from the device info window in GremlinEx 
# and there's a convenient copy code button in that window to paste it to config.py
# 3 is the axis number - X = 1, Y = 2, Z = 3, rotX = 4, roty = 5, rotz = 6, slider 1 = 7, slider 2 = 8
@left_vpc.axis(3)
def space_brake(event, vjoy):
    global brake_on
    brake_threshold = 0.8 # 80 %twist in any direction (positive or negative) - stick value is -1.0 to +1.0 with 0.0 being centered
    value = abs(event.value) 
    if not brake_on and value >= brake_threshold: 
        brake_on = True
        MacroManager().queue_macro(brake_on_macro) 
            
    elif brake_on and value < brake_threshold:
        MacroManager().queue_macro(brake_off_macro)
            
        brake_on = False
`

**Comment by muchimi** [comment]
Fixed in https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.8ex
Another QT6 surprise!

This said - I'm not sure if this particular approach will solve what you're trying to do.  I recommended the script approach in my earlier comment to address this - ping me on discord @muchimi if you need help setting up a profile script to use that sample code.
