### ISSUE TITLE
Since m44 not working

### ISSUE THREAD

**Issue by Lucarrrrr** [muchimi/JoystickGremlinEx#233]
Since v13.40.16exm44 JSG is not working anymore. M43 works fine.
There are two errors reported and JSG won't quit any more.
![1](https://github.com/user-attachments/assets/0d89db5b-df5e-4c30-b1d8-c3c7c9ef817e)
![2](https://github.com/user-attachments/assets/bc2b90cc-4338-4082-9e69-c1bafdb52c3f)
![3](https://github.com/user-attachments/assets/8ef2f77d-e05e-402b-909d-4f56e8b3fd7d)

**Comment by muchimi** [comment]
Thanks for reporting.  There is one issue (presumably solved in m47) to address JGEX not exiting if a profile was running at the time it's closed - this is due to a thread still running and thus keeping the process alive and preventing it from closing. 
https://github.com/muchimi/JoystickGremlinEx/issues/230

The other issue (hardware_device_guid member not found) will be resolved in the next patch and has to do with the introduction of the mode tab.

**Comment by muchimi** [comment]
Please see if resolved in
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m47.zip

**Comment by Lucarrrrr** [comment]
Works fine again. Thanx for your work!
