### ISSUE TITLE
JoystickGremlinEx not finding my controllers

### ISSUE THREAD

**Issue by RiceMunk** [muchimi/JoystickGremlinEx#241]
I have 4 controllers (plus the vJoy virtual device) attached to my system, as per this screenshot of the Win11 Game Controllers settings window:
![image](https://github.com/user-attachments/assets/f310be7f-88f8-4e69-a175-151e54a7f7ef)

When I'm trying to use JoystickGremlinEx to set them up, it launches fine but doesn't find any of the controllers. If I've understood it correctly, they should show up as tabs in the UI, but all I'm getting is what looks like this screenshot:
![image](https://github.com/user-attachments/assets/3fa84b7b-772c-4861-99f8-e0a0569e74bf)

The release of JoysticGremlinEx I've been trying this with is 13.40.16ex (m48R).
I have vJoy  2.1.9.1-160719 installed, but not hidHide. I've also tried with hidHide installed, but result is the same.

As per the discussion we had on Discord about this, also attached is my [system.log](https://github.com/user-attachments/files/18221291/system.log) from my most recent attempt. I've set verbose and input logging on. As you can see, the controllers are as far as I can see detected, but for whatever reason the UI doesn't reflect this.

**Comment by RiceMunk** [comment]
Also a few more things worth noting:
- This is on a pretty fresh (about 1 week) install of Windows 11 Home
- The controllers are detected by several games, such as Star Citizen, Euro Truck Simulator 2, and MS Flight Simulator

And a possibly bigger related thing of note:

The Windows Game Controllers settings menu for whatever reason is unusable beyond showing the view as per the above screenshot, because the window is completely frozen and unresponsive. It's worked fine on a previous PC build with the same controllers (though I'd never tried any JoystickGremlin with that build), but something seems to be different here and I'm not sure what.

I've found [some discussion online](https://answers.microsoft.com/en-us/windows/forum/all/controller-configuration-window-freezing-unable-to/8c0d8df6-a1fa-450e-99b6-9450c7bf1b42) of similar issues with the controller config window freezing up, but I have no Corsair stuff in my PC at least, aside from two RAM sticks by them.

**Comment by RiceMunk** [comment]
So I think there's some combination of problems with either my Crosswind and/or Bravo throttle quadrant, and a race condition happening here.

I tried unplugging devices from my setup, and one attempt with the Bravo unplugged JoystickGremlinEx seems to find all the still plugged stuff fine:
![image](https://github.com/user-attachments/assets/b61ab989-6a7f-4e55-9c13-5d9943bcef0c)

Here's the [system.log](https://github.com/user-attachments/files/18221376/system.log) from that attempt.

I can't get this reliably reproduce, but it does happen sometimes.

My working theory is that [the part where you're doing joystick device initialization](https://github.com/muchimi/JoystickGremlinEx/blob/407786660da660d03790ae55c6b4423db33a8d0a/gremlin/joystick_handling.py#L295) is falling afoul some async nonsense and not waiting for long enough to find all the devices, as for whatever reason on my system it takes longer than that part of code runs its course.

I haven't been able to test this theory myself by adding a long sleep there, since I can't get the repo to build on my own machine; the built artifact, after I setup a venv with what I think you're using for building, is complaining about missing python DLLs and I gave up trying to get it to work for now.

**Comment by RiceMunk** [comment]
Another update, it looks like plugging/unplugging controllers triggers some sort of a rediscovery of all controllers? I tried unplugging+replugging one of my controllers while JoystickGremlinEx is active, and after that it finds all of them:
![image](https://github.com/user-attachments/assets/6eba4ebe-8a2c-41c2-8b6c-0f630203b6da)

I think one workaround for whatever is going on here is either doing the replug dance, or adding a button in the interface somewhere to force rediscovery of the connected devices.

**Comment by muchimi** [comment]
Thank you for posting the log and screenshots.  What's happening from what I can tell is the first time DirectInput is initialized, it returns no devices.  Subsequently, it does.
What I've done is added a retry feature if no devices are detected to give GremlinEx 4 attempts (1 initial + 3 retries) with a sleep in the middle which allows the computer to do other things, such as initialize.
I suspect what may be happening is a driver load of some kind when DirectInput is initialized.

GremlinEx "sees" devices based on what the DirectX, specifically, DirectInput API sees, and the very first time it runs, DirectInput says "no devices".   However that changes a while later - a short while later - based on the enumeration that takes place.

I have a test version for you to try out that implements the retry feature if no devices are found during the DirectInput DLL load process - so it has ample time to do its thing.

This may not work at all but worth to see if giving it a bit more time resolves the issue.  It makes little sense to me why this would happen because DirectInput should see devices instantly - I can only presume some third party driver has to load before as there is nothing here I see internal to GremlinEx.

When you plug/unplug a device, GremlinEx detects that and goes through the same initialization routine to enumerate all devices (devices added, or devices removed).   The fact you can see devices after unplugging one or adding one later tells me that at some point, DirectInput sees the devices, just not instantly during the initialization process.

Try this and please re-attach the log file from that to see what changed.

https://github.com/muchimi/JoystickGremlinEx/releases/download/test/joystick_gremlin_13_40_16_m50_test.zip

**Comment by Lolo401** [comment]
Seems strangely familiar to my issue with incinsistent device detections.

**Comment by RiceMunk** [comment]
Thanks for looking into this.
I've been testing the version you posted, and it's getting mixed results. Most of the time it's not finding anything, and at least on one occasion it did find two of the devices, as per this screenshot:
![image](https://github.com/user-attachments/assets/34fbe87c-aab3-4b6d-8f9c-3d47c4a4c260)
and this log file: [system.log](https://github.com/user-attachments/files/18223063/system.log)
but no more.

Here's one logfile from an attempt where it didn't find anything on startup: 
[system.log](https://github.com/user-attachments/files/18223065/system.log)

There was at least one situation where I was trying it with the previous version that per the log timestamps it only found my joysticks a few *minutes* after starting JoystickGremlinEx. I suspect this is related to whatever strange issue with my machine is causing the joysticks to be slow to discover sometimes.

I'm still trying to figure out what's up with the slow discovery of my joysticks on my system, but I suspect it's the root cause here. That JoystickGremlinEx can't find them on time in its startup is just a symptom of whatever is happening.

**Comment by RiceMunk** [comment]
Ohh kay, I don't really fully understand what I did, but I think I managed to fix(?) the slow device discovery thing on my computer.

The [PDF manual for my Crosswind pedals](https://mfg-sim.com/download/MFG_Configurator_Manual_rev.05_en.pdf) mentioned on page 18 something about windows freezing during boot, and that it's related to a BIOS feature called "USB Handoff". It recommended either updating the BIOS (not applicable for me, since I already updated it), or disabling said handoff in the BIOS settings if it's there. Sure enough, there's an "XHCI Handoff" setting in my BIOS, and I disabled it, and now there's no longer any weird lag/freezing with starting up anything that uses the joysticks, and JoystickGremlinEx also finds the things just fine:
![image](https://github.com/user-attachments/assets/83e25e60-d7d2-4cb0-aeef-f24393412905)

Here's a logfile for that in case you're curious: [system.log](https://github.com/user-attachments/files/18223118/system.log)

Works even with the M48R version just fine now.

Anyhow, this issue is sort of resolved for me, but it feels important to mention this finding somewhere, in case others run into the same issue in the future.

**Comment by RiceMunk** [comment]
One more update to this saga: To experiment some more, I tried turning XHCI handoff back on, and everything still works normally now. For whatever unknown reason, toggling the XHCI handoff thing once has fixed the freezes and missing devices thing for me. I'm properly confused, but thought I'd let you know.
