### ISSUE TITLE
Vjoyremap Button Press inside Tempo acting as Toggle

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#32]
https://github.com/muchimi/JoystickGremlinEx/assets/157264378/8bf888a6-aad0-416e-8c58-6e1119fd6ff0

See capture above.

Performed on JG Ex 13.40.9Ex, downloaded 20 Apr.  Attempting to set a tempo in the GUI with a VJOYremap results in Button Press behaving somewhat like a Toggle.

Workaround: Use pulse button instead of button press.

Cheers !

**Comment by Lolo401** [comment]
Edit:
Due to the 24fps compression of the video, it is not apparent that the pulse button works.  It does, the 50ms are just not captured in the video.

**Comment by muchimi** [comment]
Update - I just uploaded a quick code change to add a Button Release option to the VjoyRemap action.
This can be used instead of a toggle function (and probably better because toggle does the same thing in this case, release a button, but a standalone release action is far more intuitive and appropriate, I think).

The pre-release zip has been updated to include these changes, which are still in the dev branch.

**Comment by Lolo401** [comment]
Will try and play with options.  I have to spend time in JG anyway to change everything to SC master mode keybinds.

**Comment by muchimi** [comment]
MM will change 7 ways to Sunday based on Yogi's feedback...   Don't hold your breath on a final mapping just yet!

**Comment by muchimi** [comment]
I've looked over the code on this, since I was doing the new button container, and the vjoymapper will not "know" if the button was pressed or not because it keeps its own status, so the behavior will be different.   I'm not sure I have a good solution for this at this point but you can use as a workaround the default mapper (unchanged) and that will behave the same in that container.

The issue with making "smart" actions is that between containers like tempo and conditions, it can lead to conflicts in logic as the action overrides whatever "state" information it was called in.

I discovered this while doing the button container, not with the button mapper, but with map keyboards because that mapper also has its own state control and, in particular, is able to send makes and breaks separately - a behavior that works very well in some circumstances, but not others.

**Comment by muchimi** [comment]
I think there are alternate ways to accomplish this right now with the new container types.
I'm going to close this for now and include this as a to-do for consideration in a future release when I have the time.
