### ISSUE TITLE
Incorrect VJOY Pairing   ....  Issue hard to describe, see capture

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#33]
https://github.com/muchimi/JoystickGremlinEx/assets/157264378/478b069d-ffd5-4ba0-bd5d-5c7c8add9484

While troubleshooting pairings with the latest JG release, the following was observed : 

Setting any pairing for my Virpil, button 11 would always result to VJOY2 button 57.  Even if pairing left blank.

Several instances of the same type have been observed. 

Cheers,

**Comment by muchimi** [comment]
Can you confirm you are not running any plugin scripts along with the mappings (so the rightmost tab has no entries that run scripts?  I ask that because some of my test scripts will assign button 57 by default and you mentioned a very specific number and that one totally rings a bell (could be a coincidence of course).
I have not yet run across a scenario where buttons are mapped incorrectly so this one is a bit strage.
Also, please attach your profile XML.  This will give me some pointers to see what data has been saved and how you did the mapping.
Lastly - use the pre-release version so it's from a known quantity including all prior bug fixes included in the pre-release.

**Comment by Lolo401** [comment]
I crosschecked my XML file and found the issue:

It appears to be linked to the Mode selection.  Vjoy 2 Btn 57 was supposed to get activated only if Mode "Salvage" was active, which is inherited from "combat".  However, in the video, i am in combat mode, not salvage.

Trying to switch modes in the GUI triggered the following:

![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/a6f2d8ed-ccfc-4f4d-8ef9-f9e4476f8e4c)

I will run some additional regression testing.

**Comment by Lolo401** [comment]
User buffoonery
