### ISSUE TITLE
Something with the UI breaks

### ISSUE THREAD

**Issue by alex-smtv** [muchimi/JoystickGremlinEx#6]
While fiddling around I discovered that something is breaking with the UI and it generates errors. I'll link a video that will tell more than a thousand words:

https://github.com/muchimi/JoystickGremlinEx/assets/13024466/a2c27549-6976-4e96-ada5-4689f7e80ecd

I can consistently make this error pop up with the exact first few steps. You'll notice the longer you watch the video that once this error shows up it will come back in all kind of place.

**Comment by muchimi** [comment]
I'll chalk that to "needs investigation" to gracefully handle that as it should not error our when you do use the feature.

I typically do not use the UI for this because I immediately go to scripting for advanced logic needs because it's a lot faster for me and can accomplish far more complex things than the UI can handle, especially when you start combining multiple state conditions.   I've enhanced the plugin support with events and decorators to track Gremlin state like mode changes, profile start and end events, and in general access to any state information is very easy to get to in a plugin to come up with complex setups like this - far more complex than the UI can handle (and faster in my book too).

This said there is no reason per se that Gremlin conditions should not work with VjoyRemap - it's not something I've used (thus tested) - hence why it's doing this.  More to add to the plate!

**Comment by alex-smtv** [comment]
I think you misunderstood one part of my findings. I talked about VjoyRemap to insinuate the error is propagating/shown in other places, but it's in no way related to it. I can make the error happen from vanilla gremlin functions only. All of this is just navigating trough the menus, I'm not using any features. That being said it seems to happen in the menus of a specific feature.

To replicate it I do these simple steps:
- Choose one physical button
- Add a Remap
- Condition tab
- Apply conditions to Action or Container, doesn't matter
- vJoy condition
- Select some random vJoy button or axis
- If it didn't trigger the error yet, it will when selecting another button/axis

And from that point the error pop up will persist. Adding new container NoOp, Description, etc. and trying to remove a container will show the error. But by fiddling with it again I think I made a discovery on the issue.

What I found is the error persisting seems to be linked with the container the error happened. I'll link a video below to showcase it. Let's say we name a container A that will produce the error by following the steps described above. When adding a container B, it can be anything (NoOp, Description, Macro, etc.), the error pop up will show every time. When removing any container other than A, the error pop up will show. However if we remove the container A, the error disappears completely.

It also seems the error is localized to a physical mapping. If we trigger the error on the physical button 2 and intentionally keep it around, when doing mappings in button 3 no error will intervene. Going back to button 2 the error will still be here until we remove the culprit container.


https://github.com/muchimi/JoystickGremlinEx/assets/13024466/1bb3b1af-d197-4d99-a264-8e791799da3f

I also have another piece of information I just found at the time of this writing. I tried to save the profile when I create a container giving the error, close the software and opening it again. The result is the error is still here behaving the same as explained before/showed in the video. So it seems like the culprit container persist with the profile if it is saved and the container not removed.

Hope these findings can help you. To be clear I'm not using the feature where the error starts to happen so it is not a priority to me. I'm just showing it to you so you are aware of it.

**Comment by muchimi** [comment]
I'll have a look when I get a chance.
Thanks,

**Comment by muchimi** [comment]
Please try again with 13.40.7ex and see if the issue is resolved now that one of the race conditions has been addressed.  It may be something else but I can't reproduce on my end at this point.  We can re-open if it persists with the updates published since then.
