### ISSUE TITLE
QoL Suggestion: Automatic GUID re-assignment based on device label

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#62]
This is a QoL suggestions:

**Issue**: GUID for USB devices and VJoy devices are assigned randomly based on a mysterious OS logic (appears to be linked to USB port selection and/or power sequence).  When a JG Ex user changes its setup (due to fresh install) or reassigns usb ports, the profile becomes unusable until all GUID's are manually modified via an editor such as VS Code.  If using a large quantity of devices and/or VJoy, this can prove challenging. 

**Suggestions**: Implement a feature to automatically re-assign the GUID's based on Device labels on request.

Thanks for your continuous support.  The latest build has been running pretty flawlessly for the last few weeks.

Cheers

**Comment by muchimi** [comment]
I'm going to close this one because we now have a pair of features I think that help with this:
(1) there is now a profile import feature that I think addresses the GUID change issue by letting you map items from one device to another.
(2) there is a built-in GUID remap feature also available, although importing the profile is probably the easier of the two as you don't need to know what the GUIDs are with method 1.
