### ISSUE TITLE
13.40.14ex (m5) - JG Ex not responding + VJoy issue when viewing current axis via input viewer

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#69]
The input viewer feature was tested using a blank profile with the setup mentioned in the previous reports.
2 Axis were remaped to VJoy 1 and 2.
The input viewer was selected and the current axis option selected on the applicable device / vjoy.

When moving the joystick, JG Ex crashed with a blank error message.

The following additional error was reported although VJoy appeared to be working fine:
![image](https://github.com/user-attachments/assets/d9b5afbb-f50d-4c12-a8cf-9c059c627b6d)
![image](https://github.com/user-attachments/assets/07223614-5020-46e0-89e0-bfc728928d19)

Log file attached.
[dill_debug.txt](https://github.com/user-attachments/files/16666858/dill_debug.txt)

**Comment by Lolo401** [comment]
Additional information:

Resetting Vjoy allowed JG Ex to start.  The same procedure was repeated with a single axis mapped.  This time, the error message was displayed before the crash:
![image](https://github.com/user-attachments/assets/3f754adc-9c89-4e82-ba67-6c61357f4017)

JG immediately reported 89 instances open in the Task Manager:
![image](https://github.com/user-attachments/assets/c8d180ce-9600-4cd4-803e-5909b6bd2637)

**Comment by muchimi** [comment]
I am having a bit of trouble following this one.  Yes, there was an issue with the event processing for the new repeater (second post), and while this may have caused the first issue as the error you received is a generic catch-all error if joysticks could not be loaded.   What I'm not getting right now is how you ended up with no devices loaded at all.
We'll have to watch this one.

**Comment by Lolo401** [comment]
Additional information:
The following error appeared randomly when closing and reponing JG Ex while troubleshooting the plugin issue:
![image](https://github.com/user-attachments/assets/de5addcb-797e-497e-b538-495058ec5de7)

In 6-9 restarts, it happened 3 times.  Notably, it appeared the first time JG Ex was launched after a fresh PC restart.  I wasn't able to identify a cause, it just happens randomly at start.

**Comment by muchimi** [comment]
If no VJOY device is found, the behavior should allow the code to continue rather than abruptly forcing an exception.  I am changing that behavior as of 13.40.14ex m8 so the UI doesn't quit and allows verbose mode to be enabled that may shed more details on the problem in the log file.

I also have encountered rare contention issues when you need to log out and log back in when a process didn't terminate correctly (this includes Python processes) but also game controller monitoring software and running games - as that can place "locks" on VJOY devices that prevents them from being used - only one process can "write" to a VJOY device at a time.   This can happen for a number of reasons - the logout/login process tends to kill these processes, although sometimes a reboot is needed, if but to eliminate false-positives and ensures that no conflict is causing this, especially after something crashed.  It is however very rare but I've encountered this after process crashes - for example when I was developing custom controllers with Arduino or Rasberry Pi and that would take down the direct input DLL very quickly and cause all sorts of problems until I restarted.

**Comment by muchimi** [comment]
I am currently unable to reproduce.  Will re-open if this happens again.
