### ISSUE TITLE
13.40.14ex (m5) - Plugins cannot be edited.

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#71]
Version m5 correctly enabled the loading of plugins.  However, trying to edit an entry by clicking on the wheel has no effect.  Creating a new entry produces the same result.  It was possible to edit the name but not modify the settings:

https://github.com/user-attachments/assets/97d4a2a5-0c52-46a4-976d-8472d6889c24

**Comment by muchimi** [comment]
I may need a bit more input here as I don't use this plugin (I don't have Virpil controllers with controllable lights).
It appears to run fine for me so I may ping you on Discord to find out what the expected behavior is.

**Comment by Lolo401** [comment]
Addditional information: Tested on m6 release candidate.

JG Ex was launched with a blank profile, the profile was loaded and 1 new instance was created and modified.  The following appeared to be working as per design:
- creating and deleting instances;
- renaming instances;
- editing instances (this time it worked....).

However, trying to save the profile, create a new profile or opening another profile after the steps above were completed resulted in the following error message:
![image](https://github.com/user-attachments/assets/d6c407d4-04bd-4eb1-8c65-c7fe004e473a)

Since saving / opening / creating new profile does not work, the only option was to close JG Ex and reopen the blank profile.

**Comment by Lolo401** [comment]
Complete video of the bug here above:

https://github.com/user-attachments/assets/d779abb5-d6b1-4596-a1f9-4b880973441b

**Comment by Lolo401** [comment]
Debug file:
[dill_debug.txt](https://github.com/user-attachments/files/16683856/dill_debug.txt)

**Comment by Lolo401** [comment]
Additional information:
JG Ex .13 and .14 m(6) were opened side-side to troubleshoot the feature.  It was realized that the instance details displayed in .14 do not match the profile but always display the default values:
![image](https://github.com/user-attachments/assets/61b3312d-9f6b-4c6a-aaa2-2ab8a92d530f)
(.13 on the Right, .14 on the Left)

**Comment by muchimi** [comment]
I discovered one issue with plugins with the back-end logic changes in that the settings were not being saved because the plugin was always returning a state of "not configured", which means the settings didn't get saved.
I have modified the logic to allow (via a new option that is now turned on by default) plugin data to be saved even if one value in the plugin is not defined (perhaps because it is unused and not marked optional).
I had to do the same for other actions as well in earlier releases as the general behavior was to not save things that are incomplete.

I think this will help solve the issue.

I tested with the VPC lights plugin, and it seems to remember the configuration now - although I can't really test it because I don't have VPC panels with lights to test with.


The fix should be in m7.
