### ISSUE TITLE
Feature request (re-request ?) - Configurable input viewer

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#73]
Feature description: Streamers / Content creators like to use some sort of joystick axis position display in this form :
![image](https://github.com/user-attachments/assets/94d4e446-fef4-4bdd-9e30-19c9042dc481)

It is useful to detail maneuvers in games such as DCS / Star Citizen.

Right now, the only option available to do so is using a browser based visualizer (joyviz) with a chromakey background and import that into OBS or any other video capture software.  However, this browser based approach is limited in features and only works with physical axis and/or buttons.  The input viewer in JG Ex already offers the possibility to display any axis (physical or virtual) input and/or button press, however the representation is meant for testing purposes only.

Having the option to toggle the input viewer to a more "instructional" layout would solve the Joyviz issues.  The option to have the background as a selectable color (for chromakey purposes) would also help.

Github link to a local browser based version of Joyviz: (https://github.com/SpaceCowboyLive/joyviz)

**Comment by muchimi** [comment]
This may be possible via hooks and seems a bit outside the scope of JGEX's input mapping.
If some sort of overlay software is available, JGEX can certainly be evaluated to see if it can send outputs to that API that would show this information.  Overlays are a complex topic (one reason they are not common outside of direct game support) because it is often graphics API specific and may also present issues with anti-hacking tools that do not like these sorts of hooks to the video pipeline.  A good thought for the future and to keep in mind.
