### ISSUE TITLE
13.40.14ex (m6) - Missing vJoy Device Tabs

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#75]
I am unsure if this is intended because of new features but the tabs allowing curves to be applied to vJoy devices no longer appear:
![image](https://github.com/user-attachments/assets/a4e95130-1ffa-4d33-9665-e06133073e7d)

I personally do not use those tabs except for the naming of the devices.

**Comment by muchimi** [comment]
Used as input you mean? The behavior change for tabs, due to the re-order, is it only shows INPUT vjoy devices to declutter the tabs.

This can be easily restored although usually the curve is applied after the remapper (so you add a curve mapper to curve the input, not the output?)

**Comment by Lolo401** [comment]
Not used as input, those are displayed just fine..

Those tabs were intended to be used in the original version of JG to enable the user to apply curves to _merged and split axis_:
![image](https://github.com/user-attachments/assets/e16d2957-ae69-4f40-a410-bf56d3342433)

Although you can still apply separate curves to the individual axis being merged, this was the only way to apply a curve to the global response.  

Personally, I prefer it this way since it declutters the tabs but I can see why another would want to do this.

**Comment by muchimi** [comment]
I want to revisit the merge feature now that JGEX supports nested actions/containers for actions setup to do that (the first example of this being the new gated axis action).
It is now possible to do merging of axes as an action because the result of the action (in this case, merged axis) can now be used to feed those actions, and that includes the ability to further modify the curve or even attach a gate to a merged axis.

I'll see if I can whip something up on this as this has been on my mind for some time and the reason I do all my axis merging as a plugin right now.

More on this in a few - shouldn't take very long (famous last words).

**Comment by muchimi** [comment]
m8 has a new merge axis action that will allow you to add a merge action to any input axis. Where it is added doesn't matter as the merge is not necessarily tied to the input.   This action uses the new ability for actions to contain sub-actions if the module is written to support this.

**Comment by muchimi** [comment]
![image](https://github.com/user-attachments/assets/89d96a6c-0c4c-460d-86ac-4cccfb62d2a1)

**Comment by muchimi** [comment]
![image](https://github.com/user-attachments/assets/cb722b61-c867-42bb-b915-4d4bbe5c4223)

**Comment by muchimi** [comment]
To add a curve to a merged axis - use the new merge action.
