### ISSUE TITLE
13.40.14ex (m11) - Error when connecting devices after JG ex is launched

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#86]
Prio: LOW
Impact: Negligible / For tracking

The following collateral issue was observed when testing m11 behavior against device connect / disconnect.

If JG Ex was launched after all USB devices were connected, everything was working as per design.  However, when connecting USB devices in quick succession after JG was launched, the following error was observed:

![image](https://github.com/user-attachments/assets/8f638eba-b12f-4dde-8e84-0e5533a31f12)

The same error was observed when disconnecting devices while JG Ex was running with the profile NOT enabled.

Workaround: Acknowledge the error, close and restart JG.

Additional troubleshooting:
The error only appears when devices are connected or disconnected in quick successions.  I was using a powered USB device like this for the testing: 
![image](https://github.com/user-attachments/assets/9994f202-0d94-47d8-bb8e-d3d11370c39d)

Waiting more than 2 seconds between connections or deconnections, everything worked as per design.  If the devices were powered up in quick successions (less than 1 sec).  The error would systematically occur.

Those powered USB HUB are typically only used with complex HOTAS / HOSAS systems to keep identical GUID values.  It is therefore an edge case and I do not recommend spending any time on this.

**Comment by Lolo401** [comment]
[dill_debug.txt](https://github.com/user-attachments/files/16789706/dill_debug.txt)

**Comment by muchimi** [comment]
This is due to a race condition depending on the complexity of the current profile - namely - the UI refreshes are triggered in quick succession when device changes occur.  If you're loading a complete USB strip - that can be lots of devices in rapid sequence, although when they fire depends on the driver initialization.
In theory, there is no issue - as there is a "lock" on device updates, meaning only one can happen at the same time.
m11 waits 200ms before firing a UI update on a new device detect.  I've increased this to 500ms which is not "instant" but provides a bit more breathing room.
The actual error has to do with the rapid reset of VJOy devices, which is a part of the current UI refresh process - so m12 will cache the devices before resetting them - that will resolve the actual error however this really speaks to the general behavior when you have rapid device changes and the UI is updating while another change is occurring.  
I'll probably queue these up as a simple timer obviously doesn't cut it.

**Comment by muchimi** [comment]
M12 includes three enhancements: increased delay for detection of new inputs to reduce UI updates, refactored mode/ui load logic, and cached vjoy device reset.
https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m

**Comment by muchimi** [comment]
Marking as resolved with the behavior changes as of m12 onward. We can re-open if it occurs again.
