### ISSUE TITLE
13.40.14ex (m14) - Unable to change Map to Mouse buttons

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#94]
The legacy Map to Mouse feature was tested in a standard container on a single button.
![image](https://github.com/user-attachments/assets/31ff5328-06a5-4fd1-be96-54b238804236)

Clicking the Mouse button button to change the button resulted in the window displayed:
![image](https://github.com/user-attachments/assets/3e4f1ec0-4255-485c-9746-4eb9fb6718a6)

However clicking any mouse button resulted in the windows error sound being heard and no change to the selection.
The pop-up remained displayed until ESC was pressed.

No workaround.

**Comment by Lolo401** [comment]
Additional information:
The same was re-attempted with Map to Mouse EX.  Same results:
![image](https://github.com/user-attachments/assets/afbec444-fa8c-4efd-af74-d35c9648a601)

Manually selecting the button instead of using the pop-up was possible but resulted in expected behavior when the profile was active.

**Comment by Lolo401** [comment]
Workaround:
Setting the following actions results in correct response:
![image](https://github.com/user-attachments/assets/ae17192c-9fe0-441d-88b2-a5ae1374544c)

It therefore appears that the issue is linked with the single click option.

**Comment by muchimi** [comment]
That is one of those "features": in debug mode, the mouse hooks are disabled so mouse event processing doesn't impact the ability to debug, but that also turns off the ability for GremlinEx to listen to mouse events, which will cause a slew of issues with any parts of JGEX that depend on these mouse events.  That is expected - when debugging.

The actual bug is the detection of debug mode when running from the packaged version and I added a fail-safe to enable mouse hooks if they need to be enabled for a specific function, so the module no longer assumes mouse hooks are running.

This new behavior will be m15.
